2025-03-20 17:26:48,743 - root - INFO - 使用的 ChromeDriver 路径: D:\gmj\workSpaces\workSpaces_pycharm\autoTest1\utils\chromedriver.exe
2025-03-20 17:26:49,355 - root - INFO - Test case test_menu_navigation started at 2025-03-20 17:26:49.355775
2025-03-20 17:26:50,441 - root - INFO - 开始登录操作
2025-03-20 17:26:52,712 - root - INFO - 已打开登录页面
2025-03-20 17:26:52,818 - root - INFO - 已输入用户名：ptuser
2025-03-20 17:26:52,898 - root - INFO - 已输入密码：qwe123
2025-03-20 17:26:53,022 - root - INFO - 验证码图片已保存到 D:\gmj\workSpaces\workSpaces_pycharm\autoTest1\config\captcha.png
2025-03-20 17:26:53,811 - root - INFO - 验证码识别结果: pⅩ4W
2025-03-20 17:26:53,902 - root - INFO - 已输入验证码: pⅩ4W，第 1 次尝试
2025-03-20 17:26:58,949 - root - WARNING - 第 1 次登录失败，重新尝试
2025-03-20 17:26:58,949 - root - INFO - 开始登录操作
2025-03-20 17:27:00,617 - root - INFO - 已打开登录页面
2025-03-20 17:27:00,713 - root - INFO - 已输入用户名：ptuser
2025-03-20 17:27:00,797 - root - INFO - 已输入密码：qwe123
2025-03-20 17:27:00,896 - root - INFO - 验证码图片已保存到 D:\gmj\workSpaces\workSpaces_pycharm\autoTest1\config\captcha.png
2025-03-20 17:27:01,621 - root - INFO - 验证码识别结果: 9:r zr
2025-03-20 17:27:01,688 - root - INFO - 已输入验证码: 9:r zr，第 2 次尝试
2025-03-20 17:27:06,749 - root - WARNING - 第 2 次登录失败，重新尝试
2025-03-20 17:27:06,750 - root - INFO - 开始登录操作
2025-03-20 17:27:07,774 - root - INFO - 已打开登录页面
2025-03-20 17:27:07,855 - root - INFO - 已输入用户名：ptuser
2025-03-20 17:27:07,921 - root - INFO - 已输入密码：qwe123
2025-03-20 17:27:08,037 - root - INFO - 验证码图片已保存到 D:\gmj\workSpaces\workSpaces_pycharm\autoTest1\config\captcha.png
2025-03-20 17:27:08,786 - root - INFO - 验证码识别结果: L45l
2025-03-20 17:27:08,850 - root - INFO - 已输入验证码: L45l，第 3 次尝试
2025-03-20 17:27:09,875 - root - INFO - 登录成功
2025-03-20 17:27:09,919 - root - INFO - Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE4NzE0NDExMjc1Mzg4MTQ5NzgiLCJleHAiOjE3NDI0OTE2MjgsInVzZXJuYW1lIjoicHR1c2VyIiwicmVhbG5hbWUiOiLns7vnu5_nrqHnkIblkZgifQ.XntDnecqbN3vdWP2-spPHjjSPelNeBVoRPStgoU1NQQ
2025-03-20 17:27:10,315 - root - INFO - Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE4NzE0NDExMjc1Mzg4MTQ5NzgiLCJleHAiOjE3NDI0OTE2MjgsInVzZXJuYW1lIjoicHR1c2VyIiwicmVhbG5hbWUiOiLns7vnu5_nrqHnkIblkZgifQ.XntDnecqbN3vdWP2-spPHjjSPelNeBVoRPStgoU1NQQ
2025-03-20 17:27:10,381 - root - INFO - 开始解析36个根菜单项
2025-03-20 17:27:10,382 - root - INFO - 共提取到255个菜单项
2025-03-20 17:27:10,382 - root - INFO - 菜单数据已保存至: d:\gmj\workSpaces\workSpaces_pycharm\autoTest1\menu.json
2025-03-20 17:27:11,432 - root - ERROR - 退出登录时出现错误: Message: element click intercepted: Element <span data-v-8ef766a4="">...</span> is not clickable at point (1866, 29). Other element would receive the click: <div class="ant-notification-notice ant-notification-notice-closable">...</div>
  (Session info: chrome=131.0.6778.70)
Stacktrace:
	GetHandleVerifier [0x00007FF675C12775+28773]
	(No symbol) [0x00007FF675B7AFB0]
	(No symbol) [0x00007FF675A1552A]
	(No symbol) [0x00007FF675A70B5E]
	(No symbol) [0x00007FF675A6E5FC]
	(No symbol) [0x00007FF675A6B7E6]
	(No symbol) [0x00007FF675A6A741]
	(No symbol) [0x00007FF675A5C970]
	(No symbol) [0x00007FF675A8EF9A]
	(No symbol) [0x00007FF675A5C1C6]
	(No symbol) [0x00007FF675A8F1B0]
	(No symbol) [0x00007FF675AAF1A4]
	(No symbol) [0x00007FF675A8ED43]
	(No symbol) [0x00007FF675A5A548]
	(No symbol) [0x00007FF675A5B6B1]
	GetHandleVerifier [0x00007FF675F3F45D+3358029]
	GetHandleVerifier [0x00007FF675F5430D+3443709]
	GetHandleVerifier [0x00007FF675F483FD+3394797]
	GetHandleVerifier [0x00007FF675CD929B+842635]
	(No symbol) [0x00007FF675B8654F]
	(No symbol) [0x00007FF675B81FA4]
	(No symbol) [0x00007FF675B8213D]
	(No symbol) [0x00007FF675B71629]
	BaseThreadInitThunk [0x00007FFE15007614+20]
	RtlUserThreadStart [0x00007FFE159426A1+33]

2025-03-20 17:27:14,652 - root - INFO - 开始登录操作
2025-03-20 17:27:16,763 - root - INFO - 已打开登录页面
2025-03-20 17:27:16,864 - root - INFO - 已输入用户名：guomj
2025-03-20 17:27:16,937 - root - INFO - 已输入密码：gmj123..
2025-03-20 17:27:17,043 - root - INFO - 验证码图片已保存到 D:\gmj\workSpaces\workSpaces_pycharm\autoTest1\config\captcha.png
2025-03-20 17:27:17,720 - root - INFO - 验证码识别结果: YybC
2025-03-20 17:27:17,790 - root - INFO - 已输入验证码: YybC，第 1 次尝试
2025-03-20 17:27:22,840 - root - WARNING - 第 1 次登录失败，重新尝试
2025-03-20 17:27:22,840 - root - INFO - 开始登录操作
2025-03-20 17:27:24,456 - root - INFO - 已打开登录页面
2025-03-20 17:27:24,545 - root - INFO - 已输入用户名：guomj
2025-03-20 17:27:24,626 - root - INFO - 已输入密码：gmj123..
2025-03-20 17:27:24,703 - root - INFO - 验证码图片已保存到 D:\gmj\workSpaces\workSpaces_pycharm\autoTest1\config\captcha.png
2025-03-20 17:27:25,509 - root - INFO - 验证码识别结果: KBN0
2025-03-20 17:27:25,578 - root - INFO - 已输入验证码: KBN0，第 2 次尝试
2025-03-20 17:27:26,935 - root - INFO - 登录成功
2025-03-20 17:27:26,959 - root - INFO - Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE4NTMyMzM5MjA5MDUwODA4MzMiLCJleHAiOjE3NDI0OTE2NDUsInVzZXJuYW1lIjoiZ3VvbWoiLCJyZWFsbmFtZSI6IumDreaipuWohyjmraPlvI8pIn0.XHDucTjwBaYuXIPKsUa87C4gHRvuQpSfRwUSR9BpY5o
2025-03-20 17:27:43,531 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000217A8BC9670>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4b4f0487db5522cfd06458311b227516/element
2025-03-20 17:27:47,614 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000217A8BC9700>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4b4f0487db5522cfd06458311b227516/element
2025-03-20 17:27:51,710 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000217A8BC9850>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4b4f0487db5522cfd06458311b227516/element
2025-03-20 17:27:55,799 - root - ERROR - 退出登录时出现错误: HTTPConnectionPool(host='localhost', port=54643): Max retries exceeded with url: /session/4b4f0487db5522cfd06458311b227516/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000217A8BC9610>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2025-03-20 17:27:59,895 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000217A8BC8290>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4b4f0487db5522cfd06458311b227516
2025-03-20 17:28:03,995 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000217A8BC8650>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/4b4f0487db5522cfd06458311b227516
2025-03-20 17:28:10,133 - root - INFO - Test case test_menu_navigation ended at 2025-03-20 17:28:10.133423
