2025-03-20 15:08:04,825 - root - INFO - 使用的 ChromeDriver 路径: D:\gmj\workSpaces\workSpaces_pycharm\autoTest1\utils\chromedriver.exe
2025-03-20 15:08:04,850 - root - INFO - Test case test_menu_navigation started at 2025-03-20 15:08:04.850314
2025-03-20 15:08:05,860 - root - INFO - 开始登录操作
2025-03-20 15:08:08,053 - root - INFO - 已打开登录页面
2025-03-20 15:08:08,175 - root - INFO - 已输入用户名：ptuser
2025-03-20 15:08:08,259 - root - INFO - 已输入密码：qwe123
2025-03-20 15:08:08,355 - root - INFO - 验证码图片已保存到 D:\gmj\workSpaces\workSpaces_pycharm\autoTest1\config\captcha.png
2025-03-20 15:08:09,115 - root - INFO - 验证码识别结果: Unh4
2025-03-20 15:08:09,190 - root - INFO - 已输入验证码: Unh4，第 1 次尝试
2025-03-20 15:08:10,269 - root - INFO - 登录成功
2025-03-20 15:08:10,322 - root - INFO - Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE4NzE0NDExMjc1Mzg4MTQ5NzgiLCJleHAiOjE3NDI0ODMyODksInVzZXJuYW1lIjoicHR1c2VyIiwicmVhbG5hbWUiOiLns7vnu5_nrqHnkIblkZgifQ.TmLvSX09TRsPnyjLMxMycWrp4Q4UiCfoA4qrg2ypspc
2025-03-20 15:08:10,331 - root - INFO - Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE4NzE0NDExMjc1Mzg4MTQ5NzgiLCJleHAiOjE3NDI0ODMyODksInVzZXJuYW1lIjoicHR1c2VyIiwicmVhbG5hbWUiOiLns7vnu5_nrqHnkIblkZgifQ.TmLvSX09TRsPnyjLMxMycWrp4Q4UiCfoA4qrg2ypspc
2025-03-20 15:08:10,374 - root - INFO - 开始解析36个根菜单项
2025-03-20 15:08:10,375 - root - INFO - 共提取到255个菜单项
2025-03-20 15:08:11,806 - root - ERROR - 退出登录时出现错误: Message: element click intercepted: Element <span data-v-8ef766a4="">...</span> is not clickable at point (1866, 29). Other element would receive the click: <div class="ant-notification-notice ant-notification-notice-closable">...</div>
  (Session info: chrome=131.0.6778.70)
Stacktrace:
	GetHandleVerifier [0x00007FF675C12775+28773]
	(No symbol) [0x00007FF675B7AFB0]
	(No symbol) [0x00007FF675A1552A]
	(No symbol) [0x00007FF675A70B5E]
	(No symbol) [0x00007FF675A6E5FC]
	(No symbol) [0x00007FF675A6B7E6]
	(No symbol) [0x00007FF675A6A741]
	(No symbol) [0x00007FF675A5C970]
	(No symbol) [0x00007FF675A8EF9A]
	(No symbol) [0x00007FF675A5C1C6]
	(No symbol) [0x00007FF675A8F1B0]
	(No symbol) [0x00007FF675AAF1A4]
	(No symbol) [0x00007FF675A8ED43]
	(No symbol) [0x00007FF675A5A548]
	(No symbol) [0x00007FF675A5B6B1]
	GetHandleVerifier [0x00007FF675F3F45D+3358029]
	GetHandleVerifier [0x00007FF675F5430D+3443709]
	GetHandleVerifier [0x00007FF675F483FD+3394797]
	GetHandleVerifier [0x00007FF675CD929B+842635]
	(No symbol) [0x00007FF675B8654F]
	(No symbol) [0x00007FF675B81FA4]
	(No symbol) [0x00007FF675B8213D]
	(No symbol) [0x00007FF675B71629]
	BaseThreadInitThunk [0x00007FFE15007614+20]
	RtlUserThreadStart [0x00007FFE159426A1+33]

2025-03-20 15:08:15,094 - root - INFO - 开始登录操作
2025-03-20 15:08:17,306 - root - INFO - 已打开登录页面
2025-03-20 15:08:17,418 - root - INFO - 已输入用户名：guomj
2025-03-20 15:08:17,489 - root - INFO - 已输入密码：gmj123..
2025-03-20 15:08:17,585 - root - INFO - 验证码图片已保存到 D:\gmj\workSpaces\workSpaces_pycharm\autoTest1\config\captcha.png
2025-03-20 15:08:18,297 - root - INFO - 验证码识别结果: c 8 AQ
2025-03-20 15:08:18,374 - root - INFO - 已输入验证码: c 8 AQ，第 1 次尝试
2025-03-20 15:08:23,419 - root - WARNING - 第 1 次登录失败，重新尝试
2025-03-20 15:08:23,419 - root - INFO - 开始登录操作
2025-03-20 15:08:25,156 - root - INFO - 已打开登录页面
2025-03-20 15:08:25,278 - root - INFO - 已输入用户名：guomj
2025-03-20 15:08:25,363 - root - INFO - 已输入密码：gmj123..
2025-03-20 15:08:25,445 - root - INFO - 验证码图片已保存到 D:\gmj\workSpaces\workSpaces_pycharm\autoTest1\config\captcha.png
2025-03-20 15:08:26,128 - root - INFO - 验证码识别结果: Fzla
2025-03-20 15:08:26,192 - root - INFO - 已输入验证码: Fzla，第 2 次尝试
2025-03-20 15:08:27,315 - root - INFO - 登录成功
2025-03-20 15:08:27,360 - root - INFO - Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjE4NTMyMzM5MjA5MDUwODA4MzMiLCJleHAiOjE3NDI0ODMzMDYsInVzZXJuYW1lIjoiZ3VvbWoiLCJyZWFsbmFtZSI6IumDreaipuWohyjmraPlvI8pIn0.3t0LvF6pf1EaqqMX3UjeVCU2VkIZwY2DeKPmZsha9d8
2025-03-20 15:08:43,861 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001836951ADB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/18cb8d5c6989945b113972774b4cd639/element
2025-03-20 15:08:47,909 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000183695198E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/18cb8d5c6989945b113972774b4cd639/element
2025-03-20 15:08:51,976 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001836951A420>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/18cb8d5c6989945b113972774b4cd639/element
2025-03-20 15:08:56,059 - root - ERROR - 退出登录时出现错误: HTTPConnectionPool(host='localhost', port=58943): Max retries exceeded with url: /session/18cb8d5c6989945b113972774b4cd639/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001836951A720>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
2025-03-20 15:09:00,111 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001836951A8D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/18cb8d5c6989945b113972774b4cd639
2025-03-20 15:09:04,177 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001836951AAE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/18cb8d5c6989945b113972774b4cd639
2025-03-20 15:09:08,267 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001836951AC60>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/18cb8d5c6989945b113972774b4cd639
2025-03-20 15:09:16,387 - root - INFO - Test case test_menu_navigation ended at 2025-03-20 15:09:16.387294
